/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as AdminImport } from './routes/_admin'
import { Route as LayoutRestrictImport } from './routes/_layout/restrict'
import { Route as LayoutProductProductIdImport } from './routes/_layout/product.$productId'
import { Route as AdminAdminLoginImport } from './routes/_admin/admin/login'
import { Route as AdminAdminAuthenticatedImport } from './routes/_admin/admin/_authenticated'
import { Route as AdminAdminAuthenticatedIndexImport } from './routes/_admin/admin/_authenticated/index'

// Create Virtual Routes

const AdminAdminImport = createFileRoute('/_admin/admin')()
const LayoutIndexLazyImport = createFileRoute('/_layout/')()
const LayoutProductsLazyImport = createFileRoute('/_layout/products')()
const LayoutLoginLazyImport = createFileRoute('/_layout/login')()
const LayoutBestSellersLazyImport = createFileRoute('/_layout/best-sellers')()
const LayoutAboutLazyImport = createFileRoute('/_layout/about')()
const LayoutSearchSearchLazyImport = createFileRoute(
  '/_layout/search/$search',
)()

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  id: '/_admin',
  getParentRoute: () => rootRoute,
} as any)

const AdminAdminRoute = AdminAdminImport.update({
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)

const LayoutIndexLazyRoute = LayoutIndexLazyImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() => import('./routes/_layout/index.lazy').then((d) => d.Route))

const LayoutProductsLazyRoute = LayoutProductsLazyImport.update({
  path: '/products',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/products.lazy').then((d) => d.Route),
)

const LayoutLoginLazyRoute = LayoutLoginLazyImport.update({
  path: '/login',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() => import('./routes/_layout/login.lazy').then((d) => d.Route))

const LayoutBestSellersLazyRoute = LayoutBestSellersLazyImport.update({
  path: '/best-sellers',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/best-sellers.lazy').then((d) => d.Route),
)

const LayoutAboutLazyRoute = LayoutAboutLazyImport.update({
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() => import('./routes/_layout/about.lazy').then((d) => d.Route))

const LayoutRestrictRoute = LayoutRestrictImport.update({
  path: '/restrict',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSearchSearchLazyRoute = LayoutSearchSearchLazyImport.update({
  path: '/search/$search',
  getParentRoute: () => LayoutRoute,
} as any).lazy(() =>
  import('./routes/_layout/search.$search.lazy').then((d) => d.Route),
)

const LayoutProductProductIdRoute = LayoutProductProductIdImport.update({
  path: '/product/$productId',
  getParentRoute: () => LayoutRoute,
} as any)

const AdminAdminLoginRoute = AdminAdminLoginImport.update({
  path: '/login',
  getParentRoute: () => AdminAdminRoute,
} as any)

const AdminAdminAuthenticatedRoute = AdminAdminAuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => AdminAdminRoute,
} as any)

const AdminAdminAuthenticatedIndexRoute =
  AdminAdminAuthenticatedIndexImport.update({
    path: '/',
    getParentRoute: () => AdminAdminAuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/restrict': {
      preLoaderRoute: typeof LayoutRestrictImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/about': {
      preLoaderRoute: typeof LayoutAboutLazyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/best-sellers': {
      preLoaderRoute: typeof LayoutBestSellersLazyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/login': {
      preLoaderRoute: typeof LayoutLoginLazyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/products': {
      preLoaderRoute: typeof LayoutProductsLazyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexLazyImport
      parentRoute: typeof LayoutImport
    }
    '/_admin/admin': {
      preLoaderRoute: typeof AdminAdminImport
      parentRoute: typeof AdminImport
    }
    '/_admin/admin/_authenticated': {
      preLoaderRoute: typeof AdminAdminAuthenticatedImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/login': {
      preLoaderRoute: typeof AdminAdminLoginImport
      parentRoute: typeof AdminAdminImport
    }
    '/_layout/product/$productId': {
      preLoaderRoute: typeof LayoutProductProductIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/search/$search': {
      preLoaderRoute: typeof LayoutSearchSearchLazyImport
      parentRoute: typeof LayoutImport
    }
    '/_admin/admin/_authenticated/': {
      preLoaderRoute: typeof AdminAdminAuthenticatedIndexImport
      parentRoute: typeof AdminAdminAuthenticatedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  AdminRoute.addChildren([
    AdminAdminRoute.addChildren([
      AdminAdminAuthenticatedRoute.addChildren([
        AdminAdminAuthenticatedIndexRoute,
      ]),
      AdminAdminLoginRoute,
    ]),
  ]),
  LayoutRoute.addChildren([
    LayoutRestrictRoute,
    LayoutAboutLazyRoute,
    LayoutBestSellersLazyRoute,
    LayoutLoginLazyRoute,
    LayoutProductsLazyRoute,
    LayoutIndexLazyRoute,
    LayoutProductProductIdRoute,
    LayoutSearchSearchLazyRoute,
  ]),
])

/* prettier-ignore-end */
